apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev-release
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pnowy/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default